spring:
  datasource:
    # url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:postgresql://ec2-54-173-77-184.compute-1.amazonaws.com:5432/d4gt3gkhl573ei
    username: jstgxezlnzwkta
    password: 580f531a393f051c5d6c751275d24735010491e1a79ec19dc91c350c0bcf9f64
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
   port: 8081 # This is the default port anyway, but you can change it here

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
      
UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
